module.exports = [
    'Stacie let me break / Quarantine to go hang out / With your cats challenge',
    'Satan works hard but / Not harder than a girl in / Quarantine trying',
    'A vlogged teen titans / Series would go so hard like / Them just being teens',
    'I bet my future / Wife is losing her mind in / Quarantine right now',
    'Only thing that could / Make quarantine worse right now / is hearing KennyG',
    'Damn twitter a lil / Ass lately ig carrying / It this quarantine',
    'Has caused me to have / A fishing firearm White / Claw and Coors Light',
    'What if you prefer / To do both at the same time / Is it a pemdas',
    'Your lip is the first / Thing i am gonna taste soon / As quarantine ends',
    'My mom be gettin / Mad at me for drinking wine / But bitch i NEED it',
    'The people not / Hornyposting during the / Quarantine master',
    'Need some shrooms so I / Can make my pro gamer move / And fast travel out',
    'Bro Quarantine is / Really doing a number / On the human race',
    'Violator is / Different from punching bag / Sana alam mo',
    'Going on three weeks / Of quarantine and I still / Need autocorrect',
    'YALL LET THIS NIGGA / DO THIS SHIT ON LIVE BUT I / CANT SHAKE THIS MONKEY',
    'About to perfect / The Toosie Slide and come out / Quarantine flexing',
    'We bout right foot up / Left foot slide left foot up right / Foot slide in the club',    
    'Arianna shut / Up its literally the / Quarantine talking',
    'If I knew my last / Yes was going to be my / Last yes for awhile',
    'Bruh he smart asl / This Club Quarantine shii / Was building up hype',
    'This quarantine got / Our people so bored even the / Aunties are twerking',
    'Lmao i thought i was / The only one at peace with / Growing my eyebrows',
    'You can gouge and tear / At your flesh to watch it heal / Because quarantine',
    'Quarantine got me / Texting my ex we need to / Wrap this shit asap',
    'New music and a / Fat ass blunt, not a bad day / Under quarantine',
    'The fact that human / Beings survived this long is / A miracle man',
    'Coven meetups to / Follow quarantine Get your / Outfits ready bitches',
    'Flagman would be the / First person in the hamlet / To break quarantine',
    'I think fist fighting / God would be easier than / Trying to lose weight',
    'We did not deserve / To be in quarantine right / After bad bunny',
    'Brb gonna rewatch / Unbreakable kimmy schmidt / Because quarantine',
    'Quarantine for me / Questioning if I wanna / Be an FBI agent',
    'Took it to the next / Step this morn and sat in my / Garden with a brew',
    'Friendly tweet to the / Twitter verse the quarantine / Pregnancy stopper',
    'Yea im quarantine / Clean so relax we done rose / Up from the bottom',
    'Oh my god i just / Remembered i can still thrif / During quarantine',
    'The best part about / Quarantine is the privilege / Of not seeing men'
];